//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.22 at 10:38:07 PM CEST 
//


package hu.documaison.bll.ws.doidata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.crossref.org/qrschema/2.0}given_name" minOccurs="0"/>
 *         &lt;element ref="{http://www.crossref.org/qrschema/2.0}surname"/>
 *         &lt;element ref="{http://www.crossref.org/qrschema/2.0}suffix" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.crossref.org/qrschema/2.0}contributor.atts"/>
 *       &lt;attribute name="first-author">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}boolean">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "givenName",
    "surname",
    "suffix"
})
@XmlRootElement(name = "contributor")
public class Contributor {

    @XmlElement(name = "given_name")
    protected GivenName givenName;
    @XmlElement(required = true)
    protected Surname surname;
    protected String suffix;
    @XmlAttribute(name = "first-author")
    protected Boolean firstAuthor;
    @XmlAttribute(name = "sequence")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String sequence;
    @XmlAttribute(name = "contributor_role")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String contributorRole;

    /**
     * Gets the value of the givenName property.
     * 
     * @return
     *     possible object is
     *     {@link GivenName }
     *     
     */
    public GivenName getGivenName() {
        return givenName;
    }

    /**
     * Sets the value of the givenName property.
     * 
     * @param value
     *     allowed object is
     *     {@link GivenName }
     *     
     */
    public void setGivenName(GivenName value) {
        this.givenName = value;
    }

    /**
     * Gets the value of the surname property.
     * 
     * @return
     *     possible object is
     *     {@link Surname }
     *     
     */
    public Surname getSurname() {
        return surname;
    }

    /**
     * Sets the value of the surname property.
     * 
     * @param value
     *     allowed object is
     *     {@link Surname }
     *     
     */
    public void setSurname(Surname value) {
        this.surname = value;
    }

    /**
     * Gets the value of the suffix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuffix() {
        return suffix;
    }

    /**
     * Sets the value of the suffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuffix(String value) {
        this.suffix = value;
    }

    /**
     * Gets the value of the firstAuthor property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFirstAuthor() {
        return firstAuthor;
    }

    /**
     * Sets the value of the firstAuthor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFirstAuthor(Boolean value) {
        this.firstAuthor = value;
    }

    /**
     * Gets the value of the sequence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSequence() {
        return sequence;
    }

    /**
     * Sets the value of the sequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSequence(String value) {
        this.sequence = value;
    }

    /**
     * Gets the value of the contributorRole property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContributorRole() {
        return contributorRole;
    }

    /**
     * Sets the value of the contributorRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContributorRole(String value) {
        this.contributorRole = value;
    }

}
