//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.22 at 10:38:07 PM CEST 
//


package hu.documaison.bll.ws.doidata;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{http://www.crossref.org/qrschema/2.0}doi" minOccurs="0"/>
 *         &lt;element ref="{http://www.crossref.org/qrschema/2.0}issn" maxOccurs="2" minOccurs="0"/>
 *         &lt;element ref="{http://www.crossref.org/qrschema/2.0}isbn" maxOccurs="6" minOccurs="0"/>
 *         &lt;element ref="{http://www.crossref.org/qrschema/2.0}series_title" minOccurs="0"/>
 *         &lt;element ref="{http://www.crossref.org/qrschema/2.0}journal_title" minOccurs="0"/>
 *         &lt;element ref="{http://www.crossref.org/qrschema/2.0}volume_title" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element ref="{http://www.crossref.org/qrschema/2.0}author" minOccurs="0"/>
 *           &lt;element ref="{http://www.crossref.org/qrschema/2.0}contributors" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.crossref.org/qrschema/2.0}volume" minOccurs="0"/>
 *         &lt;element ref="{http://www.crossref.org/qrschema/2.0}issue" minOccurs="0"/>
 *         &lt;element ref="{http://www.crossref.org/qrschema/2.0}first_page" minOccurs="0"/>
 *         &lt;element ref="{http://www.crossref.org/qrschema/2.0}last_page" minOccurs="0"/>
 *         &lt;element ref="{http://www.crossref.org/qrschema/2.0}item_number" minOccurs="0"/>
 *         &lt;element ref="{http://www.crossref.org/qrschema/2.0}edition_number" minOccurs="0"/>
 *         &lt;element ref="{http://www.crossref.org/qrschema/2.0}component_number" minOccurs="0"/>
 *         &lt;element ref="{http://www.crossref.org/qrschema/2.0}year" maxOccurs="6" minOccurs="0"/>
 *         &lt;element ref="{http://www.crossref.org/qrschema/2.0}publication_type" minOccurs="0"/>
 *         &lt;element ref="{http://www.crossref.org/qrschema/2.0}article_title" minOccurs="0"/>
 *         &lt;element ref="{http://www.crossref.org/qrschema/2.0}institution_name" minOccurs="0"/>
 *         &lt;element ref="{http://www.crossref.org/qrschema/2.0}identifier" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.crossref.org/qrschema/2.0}msg" minOccurs="0"/>
 *         &lt;element ref="{http://www.crossref.org/qrschema/2.0}component_list" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="key">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="128"/>
 *             &lt;minLength value="1"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="enable-multiple-hits" default="false">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}boolean">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="forward-match" default="false">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}boolean">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="status">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="resolved"/>
 *             &lt;enumeration value="unresolved"/>
 *             &lt;enumeration value="multiresolved"/>
 *             &lt;enumeration value="malformed"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="fl_count">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "doiOrIssnOrIsbn"
})
@XmlRootElement(name = "query")
public class Query {

    @XmlElements({
        @XmlElement(name = "doi", type = Doi.class),
        @XmlElement(name = "issn", type = Issn.class),
        @XmlElement(name = "isbn", type = Isbn.class),
        @XmlElement(name = "series_title", type = SeriesTitle.class),
        @XmlElement(name = "journal_title", type = JournalTitle.class),
        @XmlElement(name = "volume_title", type = VolumeTitle.class),
        @XmlElement(name = "author", type = Author.class),
        @XmlElement(name = "contributors", type = Contributors.class),
        @XmlElement(name = "volume", type = Volume.class),
        @XmlElement(name = "issue", type = Issue.class),
        @XmlElement(name = "first_page", type = FirstPage.class),
        @XmlElement(name = "last_page", type = LastPage.class),
        @XmlElement(name = "item_number", type = ItemNumber.class),
        @XmlElement(name = "edition_number", type = EditionNumber.class),
        @XmlElement(name = "component_number", type = ComponentNumber.class),
        @XmlElement(name = "year", type = Year.class),
        @XmlElement(name = "publication_type", type = PublicationType.class),
        @XmlElement(name = "article_title", type = ArticleTitle.class),
        @XmlElement(name = "institution_name", type = InstitutionName.class),
        @XmlElement(name = "identifier", type = Identifier.class),
        @XmlElement(name = "msg", type = String.class),
        @XmlElement(name = "component_list", type = ComponentList.class)
    })
    protected List<Object> doiOrIssnOrIsbn;
    @XmlAttribute(name = "key")
    protected String key;
    @XmlAttribute(name = "enable-multiple-hits")
    protected Boolean enableMultipleHits;
    @XmlAttribute(name = "forward-match")
    protected Boolean forwardMatch;
    @XmlAttribute(name = "status")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String status;
    @XmlAttribute(name = "fl_count")
    protected BigInteger flCount;

    /**
     * Gets the value of the doiOrIssnOrIsbn property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the doiOrIssnOrIsbn property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDoiOrIssnOrIsbn().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Doi }
     * {@link Issn }
     * {@link Isbn }
     * {@link SeriesTitle }
     * {@link JournalTitle }
     * {@link VolumeTitle }
     * {@link Author }
     * {@link Contributors }
     * {@link Volume }
     * {@link Issue }
     * {@link FirstPage }
     * {@link LastPage }
     * {@link ItemNumber }
     * {@link EditionNumber }
     * {@link ComponentNumber }
     * {@link Year }
     * {@link PublicationType }
     * {@link ArticleTitle }
     * {@link InstitutionName }
     * {@link Identifier }
     * {@link String }
     * {@link ComponentList }
     * 
     * 
     */
    public List<Object> getDoiOrIssnOrIsbn() {
        if (doiOrIssnOrIsbn == null) {
            doiOrIssnOrIsbn = new ArrayList<Object>();
        }
        return this.doiOrIssnOrIsbn;
    }

    /**
     * Gets the value of the key property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKey(String value) {
        this.key = value;
    }

    /**
     * Gets the value of the enableMultipleHits property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isEnableMultipleHits() {
        if (enableMultipleHits == null) {
            return false;
        } else {
            return enableMultipleHits;
        }
    }

    /**
     * Sets the value of the enableMultipleHits property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEnableMultipleHits(Boolean value) {
        this.enableMultipleHits = value;
    }

    /**
     * Gets the value of the forwardMatch property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isForwardMatch() {
        if (forwardMatch == null) {
            return false;
        } else {
            return forwardMatch;
        }
    }

    /**
     * Sets the value of the forwardMatch property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setForwardMatch(Boolean value) {
        this.forwardMatch = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the flCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFlCount() {
        return flCount;
    }

    /**
     * Sets the value of the flCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFlCount(BigInteger value) {
        this.flCount = value;
    }

}
