package hu.documaison.doiwsproxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2013-05-08T13:50:18.972+02:00
 * Generated source version: 2.7.4
 * 
 */
@WebService(targetNamespace = "http://doiwsproxy.documaison.hu/", name = "DOIWsProxy")
@XmlSeeAlso({net.java.dev.jaxb.array.ObjectFactory.class, ObjectFactory.class})
public interface DOIWsProxy {

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://doiwsproxy.documaison.hu/DOIWsProxy/queryRequest", output = "http://doiwsproxy.documaison.hu/DOIWsProxy/queryResponse")
    @RequestWrapper(localName = "query", targetNamespace = "http://doiwsproxy.documaison.hu/", className = "hu.documaison.doiwsproxy.Query")
    @WebMethod
    @ResponseWrapper(localName = "queryResponse", targetNamespace = "http://doiwsproxy.documaison.hu/", className = "hu.documaison.doiwsproxy.QueryResponse")
    public java.util.List<net.java.dev.jaxb.array.StringArray> query(
        @WebParam(name = "doi", targetNamespace = "")
        java.lang.String doi,
        @WebParam(name = "key", targetNamespace = "")
        java.lang.String key
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://doiwsproxy.documaison.hu/DOIWsProxy/queryAuthorRequest", output = "http://doiwsproxy.documaison.hu/DOIWsProxy/queryAuthorResponse")
    @RequestWrapper(localName = "queryAuthor", targetNamespace = "http://doiwsproxy.documaison.hu/", className = "hu.documaison.doiwsproxy.QueryAuthor")
    @WebMethod
    @ResponseWrapper(localName = "queryAuthorResponse", targetNamespace = "http://doiwsproxy.documaison.hu/", className = "hu.documaison.doiwsproxy.QueryAuthorResponse")
    public java.lang.String queryAuthor(
        @WebParam(name = "doi", targetNamespace = "")
        java.lang.String doi,
        @WebParam(name = "key", targetNamespace = "")
        java.lang.String key
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://doiwsproxy.documaison.hu/DOIWsProxy/queryTitleRequest", output = "http://doiwsproxy.documaison.hu/DOIWsProxy/queryTitleResponse")
    @RequestWrapper(localName = "queryTitle", targetNamespace = "http://doiwsproxy.documaison.hu/", className = "hu.documaison.doiwsproxy.QueryTitle")
    @WebMethod
    @ResponseWrapper(localName = "queryTitleResponse", targetNamespace = "http://doiwsproxy.documaison.hu/", className = "hu.documaison.doiwsproxy.QueryTitleResponse")
    public java.lang.String queryTitle(
        @WebParam(name = "doi", targetNamespace = "")
        java.lang.String doi,
        @WebParam(name = "key", targetNamespace = "")
        java.lang.String key
    );
}
