package hu.documaison.doiwsproxy;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2013-05-08T13:50:19.024+02:00
 * Generated source version: 2.7.4
 * 
 */
@WebServiceClient(name = "DOIWsProxy", 
                  wsdlLocation = "DOIWsProxy.wsdl",
                  targetNamespace = "http://doiwsproxy.documaison.hu/") 
public class DOIWsProxy_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://doiwsproxy.documaison.hu/", "DOIWsProxy");
    public final static QName DOIWsProxyPort = new QName("http://doiwsproxy.documaison.hu/", "DOIWsProxyPort");
    static {
        URL url = DOIWsProxy_Service.class.getResource("DOIWsProxy.wsdl");
        if (url == null) {
            url = DOIWsProxy_Service.class.getClassLoader().getResource("DOIWsProxy.wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(DOIWsProxy_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "DOIWsProxy.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public DOIWsProxy_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DOIWsProxy_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DOIWsProxy_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns DOIWsProxy
     */
    @WebEndpoint(name = "DOIWsProxyPort")
    public DOIWsProxy getDOIWsProxyPort() {
        return super.getPort(DOIWsProxyPort, DOIWsProxy.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DOIWsProxy
     */
    @WebEndpoint(name = "DOIWsProxyPort")
    public DOIWsProxy getDOIWsProxyPort(WebServiceFeature... features) {
        return super.getPort(DOIWsProxyPort, DOIWsProxy.class, features);
    }

}
